const YOUR_NAME = 'YOUR_NAME';
const YOUR_CONTACT_NO = 'YOUR_CONTACT_NO';
const TOKEN = 'TOKEN';
const YOUR_INTRODUCTION = 'YOUR_INTRODUCTION';

export { TOKEN, YOUR_NAME, YOUR_CONTACT_NO, YOUR_INTRODUCTION };
